export default {
    canvasWidth: 150,
    canvasHeight: 200,
    fontStyle: '40px Calibri',
    cornerFontStyle: '20px Calibri',
    offset: 10,
    iconWidth: 15,
    iconHeight: 20,
    spadeColor: 'black',
    clubColor: 'black',
    heartColor: 'red',
    diamondColor: 'red',
    backColor: 'red',
    backgroundColor: 'white',
    selectedColor: 'skyblue',
    numBackLines: 30,
    spaceColor: 'darkgray',
};