export default {
    canvasWidth: 150,
    canvasHeight: 200,
    fontStyle: '50px Calibri',
    cornerFontStyle: '30px Calibri',
    offset: 10,
    iconWidth: 30,
    iconHeight: 35,
    spadeColor: 'black',
    clubColor: 'black',
    heartColor: 'red',
    diamondColor: 'red',
    backColor: 'red',
    backgroundColor: 'white',
    selectedColor: 'skyblue',
    numBackLines: 40,
    spaceColor: 'darkgray',
};